version: 2

models:
  - name: dim_customer
    columns:
      - name: customer_id
        tests: [not_null, unique]

  - name: fct_revenue_clean
    columns:
      - name: customer_id
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dim_customer')
                field: customer_id
      - name: period
        tests: [not_null]
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns: ['customer_id', 'period']

  - name: fct_time
    columns:
      - name: customer_id
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dim_customer')
                field: customer_id
      - name: period
        tests: [not_null]
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns: ['customer_id', 'period']

  - name: fct_profit
    columns:
      - name: customer_id
        tests:
          - not_null
          - unique
          - relationships:
              arguments:
                to: ref('dim_customer')
                field: customer_id

  - name: modeling_dataset
    columns:
      - name: customer_id
        tests: [not_null, unique]
