version: 2

models:
  - name: dim_customer
    tests:
      - unique:
          column_name: customer_id
      - not_null:
          column_name: customer_id

  - name: fct_revenue_clean
    tests:
      - relationships:
          column_name: customer_id
          to: ref('dim_customer')
          field: customer_id

  - name: fct_time
    tests:
      - relationships:
          column_name: customer_id
          to: ref('dim_customer')
          field: customer_id

  - name: fct_profit
    tests:
      - relationships:
          column_name: customer_id
          to: ref('dim_customer')
          field: customer_id

  - name: modeling_dataset
    tests:
      - unique:
          column_name: customer_id
